<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <ProjectReference Include="..\..\src\Correntra.Core\Correntra.Core.csproj" />
    <ProjectReference Include="..\..\src\Correntra.Transfer\Correntra.Transfer.csproj" />
    <ProjectReference Include="..\..\src\Correntra.Media\Correntra.Media.csproj" />
    <ProjectReference Include="..\..\src\Correntra.Infrastructure\Correntra.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Correntra.Agent\Correntra.Agent.csproj" />
    <ProjectReference Include="..\..\src\Correntra.NativeHost\Correntra.NativeHost.csproj" />
  </ItemGroup>

</Project>
