<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <RootNamespace>Correntra.Platform.Windows</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Correntra.Core\Correntra.Core.csproj" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>

</Project>
