<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Correntra.Media</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Correntra.Core\Correntra.Core.csproj" />
    <ProjectReference Include="..\Correntra.Transfer\Correntra.Transfer.csproj" />
  </ItemGroup>

</Project>
