using System.ComponentModel;
using System.Globalization;
using Avalonia;

namespace Correntra.Desktop.Services;

/// <summary>
/// Lightweight, dependency-free runtime localization for the desktop shell.
/// Every visible string is addressed by a stable resource key so changing the
/// language also refreshes controls that are not part of the visual tree, such
/// as DataGrid columns and native menu flyouts.
/// </summary>
public sealed class LocalizationService : INotifyPropertyChanged
{
    private static readonly Lazy<Dictionary<string, Dictionary<string, string>>> LazyTranslations =
        new(() => new Dictionary<string, Dictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["tr"] = Turkish!,
            ["en"] = English!,
        });

    private string languageCode = "tr";

    private LocalizationService()
    {
    }

    public static LocalizationService Current { get; } = new();

    private static Dictionary<string, Dictionary<string, string>> Translations => LazyTranslations.Value;

    public event PropertyChangedEventHandler? PropertyChanged;

    public string LanguageCode => languageCode;

    public string this[string key] => Translations[languageCode].TryGetValue(key, out var value)
        ? value
        : English.TryGetValue(key, out var fallback) ? fallback : key;

    public void InitializeFromSystemCulture()
    {
        var systemLanguage = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        SetLanguage(systemLanguage.Equals("en", StringComparison.OrdinalIgnoreCase) ? "en" : "tr");
    }

    /// <summary>
    /// Startup path: honour the language the user saved in Settings; fall back
    /// to the system culture only when no setting has been persisted yet.
    /// </summary>
    public void InitializeFromSettings()
    {
        string? storedLanguage = Services.DesktopSettingsStore.Load().Language;
        SetLanguage(string.IsNullOrWhiteSpace(storedLanguage) ? "tr" : storedLanguage);
    }

    public void SetLanguage(string requestedLanguage)
    {
        var normalized = requestedLanguage.Equals("en", StringComparison.OrdinalIgnoreCase) ? "en" : "tr";
        languageCode = normalized;

        var culture = CultureInfo.GetCultureInfo(normalized == "tr" ? "tr-TR" : "en-US");
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
        ApplyApplicationResources();
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(string.Empty));
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(LanguageCode)));
    }

    public void ApplyApplicationResources()
    {
        if (Application.Current is not { } application)
        {
            return;
        }

        foreach (var pair in Translations[languageCode])
        {
            application.Resources[pair.Key] = pair.Value;
        }
    }

    private static Dictionary<string, string> Turkish { get; } = new(StringComparer.Ordinal)
    {
        ["App.Name"] = "Correntra Downloader",
        ["App.Tagline"] = "Akışı yakala. Hızla tamamla.",
        ["Common.Add"] = "Ekle",
        ["Common.Apply"] = "Uygula",
        ["Common.Browse"] = "Gözat…",
        ["Common.Cancel"] = "İptal",
        ["Common.Close"] = "Kapat",
        ["Common.Enabled"] = "Açık",
        ["Common.No"] = "Hayır",
        ["Common.Ok"] = "Tamam",
        ["Common.Save"] = "Kaydet",
        ["Common.SelectAll"] = "Tümünü seç",
        ["Common.Yes"] = "Evet",
        ["Title.Minimize"] = "Küçült",
        ["Title.Maximize"] = "Ekranı kapla",
        ["Title.Restore"] = "Geri yükle",
        ["Title.Close"] = "Kapat",
        ["Menu.Tasks"] = "Görevler",
        ["Menu.File"] = "Dosya",
        ["Menu.Downloads"] = "İndirmeler",
        ["Menu.View"] = "Görünüm",
        ["Menu.Help"] = "Yardım",
        ["Menu.AddUrl"] = "URL Ekle…",
        ["Menu.Media"] = "Yakalanan medyayı aç…",
        ["Menu.Import"] = "Bağlantı listesini içe aktar…",
        ["Menu.Exit"] = "Çıkış",
        ["Menu.OpenFile"] = "Dosyayı aç",
        ["Menu.OpenFolder"] = "Klasörü aç",
        ["Menu.Resume"] = "Devam et",
        ["Menu.Pause"] = "Duraklat",
        ["Menu.Stop"] = "Durdur",
        ["Menu.Delete"] = "Sil",
        ["Menu.DeleteCompleted"] = "Tamamlananları temizle",
        ["Menu.SelectAll"] = "Tümünü seç",
        ["Menu.Options"] = "Seçenekler…",
        ["Menu.Scheduler"] = "Programlayıcı…",
        ["Menu.DarkTheme"] = "Koyu tema",
        ["Menu.LightTheme"] = "Açık tema",
        ["Menu.Turkish"] = "Türkçe",
        ["Menu.English"] = "English",
        ["Menu.About"] = "Correntra hakkında",
        ["Toolbar.AddUrl"] = "URL Ekle",
        ["Toolbar.Resume"] = "Devam Et",
        ["Toolbar.Pause"] = "Duraklat",
        ["Toolbar.Stop"] = "Durdur",
        ["Toolbar.Delete"] = "Sil",
        ["Toolbar.Options"] = "Seçenekler",
        ["Toolbar.Scheduler"] = "Programla",
        ["Toolbar.StartQueue"] = "K. Başlat",
        ["Toolbar.StopQueue"] = "K. Durdur",
        ["Toolbar.Media"] = "Medya",
        ["Sidebar.Categories"] = "KATEGORİLER",
        ["Category.All"] = "Tüm İndirmeler",
        ["Category.Compressed"] = "Sıkıştırılmış",
        ["Category.Documents"] = "Belgeler",
        ["Category.Music"] = "Müzik",
        ["Category.Programs"] = "Programlar",
        ["Category.Video"] = "Video",
        ["Category.Images"] = "Görseller",
        ["Category.Unfinished"] = "Tamamlanmayan",
        ["Category.Finished"] = "Tamamlanan",
        ["Category.Grabber"] = "Site yakalama projeleri",
        ["Category.Queues"] = "Kuyruklar",
        ["Category.MainQueue"] = "Ana kuyruk",
        ["Search.Placeholder"] = "İndirmelerde ara",
        ["List.EmptyTitle"] = "İndirme listesi hazır",
        ["List.EmptyBody"] = "Yeni bir bağlantı ekleyin veya tarayıcı eklentisiyle bir indirme başlatın.",
        ["List.EmptyAction"] = "İlk URL'yi ekle",
        ["Column.Name"] = "Dosya adı",
        ["Column.Category"] = "Kategori",
        ["Column.Size"] = "Boyut",
        ["Column.Status"] = "Durum",
        ["Column.Progress"] = "İlerleme",
        ["Column.Remaining"] = "Kalan süre",
        ["Column.Speed"] = "Aktarım oranı",
        ["Column.Added"] = "Eklenme",
        ["Column.Description"] = "Açıklama",
        ["Status.Ready"] = "Hazır",
        ["Status.Selected"] = "{0} öğe seçili",
        ["Status.Total"] = "Toplam: {0}",
        ["Status.Active"] = "Etkin: {0}",
        ["Status.Speed"] = "Hız: {0}",
        ["Status.ExtensionConnected"] = "Tarayıcı yakalama açık",
        ["Status.ExtensionDisconnected"] = "Tarayıcı bekleniyor",
        ["Status.AgentUnavailable"] = "Correntra Agent bağlantısı kurulamadı.",
        ["Status.CommandAccepted"] = "İşlem arka plan hizmetine iletildi.",
        ["Status.CommandRejected"] = "İşlem tamamlanamadı: {0}",
        ["Status.UnknownError"] = "Bilinmeyen hata",
        ["Status.CannotOpenFolder"] = "Klasör açılamadı.",
        ["Status.CannotOpenFile"] = "Dosya açılamadı.",
        ["Menu.CopyUrl"] = "İndirme adresini kopyala",
        ["Menu.ShowInExplorer"] = "Klasörde göster",
        ["Menu.OpenContainingFolder"] = "Klasörü aç",
        ["State.Pending"] = "Hazırlanıyor",
        ["State.Queued"] = "Kuyrukta",
        ["State.NeedsInput"] = "Onay bekleniyor",
        ["State.Downloading"] = "İndiriliyor",
        ["State.Finalizing"] = "Birleştiriliyor",
        ["State.Paused"] = "Duraklatıldı",
        ["State.Completed"] = "Tamamlandı",
        ["State.Failed"] = "Başarısız",
        ["State.Cancelled"] = "İptal edildi",
        ["Update.Title"] = "Yeni Correntra sürümü hazır",
        ["Update.Version"] = "Sürüm {0}",
        ["Update.NoNotes"] = "Bu sürüm için ek not bulunmuyor.",
        ["Update.Later"] = "Daha sonra",
        ["Update.Install"] = "Kur",
        ["Update.Toast.Heading"] = "{0} sürümü çıktı",
        ["Update.Toast.Body"] = "Correntra yeni bir sürüm buldu. Şimdi kurmak ister misin?",
        ["Dialog.AddUrl.Title"] = "Yeni indirme adresi",
        ["Dialog.AddUrl.Heading"] = "Bir bağlantı ekleyin",
        ["Dialog.AddUrl.Description"] = "HTTP veya HTTPS indirme adresini yapıştırın. Bağlantı, indirme başlamadan önce güvenli biçimde incelenir.",
        ["Dialog.AddUrl.Url"] = "İndirme adresi",
        ["Dialog.AddUrl.Placeholder"] = "https://örnek.com/dosya.zip",
        ["Dialog.AddUrl.FromClipboard"] = "Panodan yapıştır",
        ["Dialog.AddUrl.Invalid"] = "Geçerli bir HTTP veya HTTPS adresi girin.",
        ["Dialog.Confirm.Title"] = "İndirme bilgisi",
        ["Dialog.Confirm.Heading"] = "Dosya indirilmeye hazır",
        ["Dialog.Confirm.Source"] = "Kaynak",
        ["Dialog.Confirm.FileName"] = "Dosya adı",
        ["Dialog.Confirm.Category"] = "Kategori",
        ["Dialog.Confirm.Destination"] = "Kaydedilecek klasör",
        ["Dialog.Confirm.Size"] = "Dosya boyutu",
        ["Dialog.Confirm.UnknownSize"] = "Hesaplanıyor…",
        ["Dialog.Confirm.Remember"] = "Bu kategori için bu yolu hatırla",
        ["Dialog.Confirm.Now"] = "İndirmeyi başlat",
        ["Dialog.Confirm.Later"] = "Daha sonra indir",
        ["Dialog.Media.Title"] = "Medya indirme seçenekleri",
        ["Dialog.Media.Heading"] = "Kalite ve biçim seçin",
        ["Dialog.Media.Description"] = "Görüntü ve ses parçaları indirme tamamlandığında otomatik olarak birleştirilir.",
        ["Dialog.Media.Video"] = "Video kalitesi",
        ["Dialog.Media.Audio"] = "Ses kalitesi",
        ["Dialog.Media.Format"] = "Çıkış biçimi",
        ["Dialog.Media.Subtitles"] = "Altyazılar",
        ["Dialog.Media.AudioOnly"] = "Yalnızca sesi kaydet",
        ["Dialog.Media.Metadata"] = "Başlık, sanatçı ve kapak bilgisini ekle",
        ["Dialog.Media.Approximate"] = "Yaklaşık boyut",
        ["Dialog.Media.Download"] = "Medyayı indir",
        ["Dialog.Schedule.Title"] = "Kuyruk programlayıcı",
        ["Dialog.Schedule.Heading"] = "Ana kuyruk çalışma planı",
        ["Dialog.Schedule.Enabled"] = "Programı etkinleştir",
        ["Dialog.Schedule.Days"] = "Çalışma günleri",
        ["Dialog.Schedule.Start"] = "Başlangıç",
        ["Dialog.Schedule.Stop"] = "Bitiş",
        ["Dialog.Schedule.Concurrent"] = "Aynı anda indirilecek dosya",
        ["Dialog.Schedule.SpeedLimit"] = "Hız sınırı (KB/sn, 0 = sınırsız)",
        ["Dialog.Schedule.Action"] = "Kuyruk tamamlandığında",
        ["Dialog.Schedule.ActionNone"] = "Bir şey yapma",
        ["Dialog.Schedule.ActionSleep"] = "Bilgisayarı uykuya al",
        ["Dialog.Schedule.ActionShutdown"] = "Bilgisayarı kapat",
        ["Day.Mon"] = "Pzt",
        ["Day.Tue"] = "Sal",
        ["Day.Wed"] = "Çar",
        ["Day.Thu"] = "Per",
        ["Day.Fri"] = "Cum",
        ["Day.Sat"] = "Cmt",
        ["Day.Sun"] = "Paz",
        ["Settings.Title"] = "Correntra seçenekleri",
        ["Settings.General"] = "Genel",
        ["Settings.Browser"] = "Tarayıcı",
        ["Settings.Transfers"] = "Aktarımlar",
        ["Settings.Categories"] = "Kategoriler",
        ["Settings.Scheduler"] = "Programlayıcı",
        ["Settings.Privacy"] = "Gizlilik",
        ["Settings.Updates"] = "Güncellemeler",
        ["Settings.General.Heading"] = "Genel davranış",
        ["Settings.General.StartWindows"] = "Windows açıldığında Correntra'yı başlat",
        ["Settings.General.Tray"] = "Kapat düğmesinde sistem tepsisine küçült",
        ["Settings.General.Notifications"] = "İndirme tamamlanınca bildirim göster",
        ["Settings.General.Clipboard"] = "Panodaki indirme bağlantılarını algıla",
        ["Settings.General.Theme"] = "Görünüm",
        ["Settings.General.Language"] = "Dil",
        ["Settings.Browser.Heading"] = "Tarayıcı entegrasyonu",
        ["Settings.Browser.Capture"] = "Chrome ve Edge indirmelerini devral",
        ["Settings.Browser.Media"] = "Sayfalarda video/müzik indirme panelini göster",
        ["Settings.Browser.Session"] = "Giriş gerektiren indirmeler için geçici oturum bilgisini kullan",
        ["Settings.Browser.Exceptions"] = "Devralınmayacak siteler",
        ["Settings.Browser.Extensions"] = "Devralınmayacak uzantılar",
        ["Settings.Transfers.Heading"] = "Aktarım performansı",
        ["Settings.Transfers.Concurrent"] = "Azami eşzamanlı indirme",
        ["Settings.Transfers.Segments"] = "İndirme başına bağlantı sayısı",
        ["Settings.Transfers.GlobalLimit"] = "Genel hız sınırı (KB/sn, 0 = sınırsız)",
        ["Settings.Transfers.Retry"] = "Geçici hataları otomatik yeniden dene",
        ["Settings.Categories.Heading"] = "Dosya türü yönlendirme",
        ["Settings.Categories.Description"] = "Uzantılar, varsayılan indirme klasörü altındaki güvenli kategori klasörlerine yönlendirilir.",
        ["Settings.Scheduler.Heading"] = "Kuyruk ve zamanlama",
        ["Settings.Scheduler.Description"] = "Ayrıntılı gün ve saat kurallarını Kuyruk Programlayıcı'dan düzenleyin.",
        ["Settings.Scheduler.Open"] = "Programlayıcıyı aç",
        ["Settings.Privacy.Heading"] = "Gizlilik ve tanılama",
        ["Settings.Privacy.NoAds"] = "Correntra reklam veya kullanıcı takibi yapmaz.",
        ["Settings.Privacy.Crash"] = "Çökme raporunu yalnızca onay verdiğimde gönder",
        ["Settings.Privacy.History"] = "Tamamlanan indirme geçmişini sakla",
        ["Settings.Privacy.Clear"] = "Yerel geçmişi temizle",
        ["Settings.VirusTotal.Heading"] = "VirusTotal taraması (isteğe bağlı)",
        ["Settings.VirusTotal.Enable"] = "Tamamlanan indirmeleri VirusTotal ile denetle",
        ["Settings.VirusTotal.ApiKey"] = "VirusTotal API anahtarı (yalnızca dosyanın SHA-256 özeti gönderilir)",
        ["Settings.VirusTotal.Get"] = "Ücretsiz anahtar al",
        ["ExtSetup.Title"] = "Tarayıcı eklentisi kurulumu",
        ["ExtSetup.Heading"] = "Tarayıcı yakalamayı etkinleştir",
        ["ExtSetup.Subtitle"] = "Chrome/Edge'teki indirmeleri ve videoları Correntra'ya yönlendirin. Yaklaşık 30 saniye sürer.",
        ["ExtSetup.BrowserLine"] = "Algılanan tarayıcılar: {0}",
        ["ExtSetup.NoBrowser"] = "Chromium tarayıcı bulunamadı (Chrome, Edge veya Brave kurun)",
        ["ExtSetup.Step1"] = "Eklenti klasörünü açın (yol panoya kopyalandı)",
        ["ExtSetup.OpenFolder"] = "Klasörü aç",
        ["ExtSetup.Step2"] = "chrome://extensions sayfasını açın, sağ üstten Geliştirici modunu açın",
        ["ExtSetup.OpenPage"] = "Eklenti sayfasını aç",
        ["ExtSetup.Step3"] = "\"Paketlenmemiş öğe yükle\"ye tıklayın, yapıştırın (Ctrl+V) ve klasörü seçin",
        ["ExtSetup.PathCopied"] = "Yol zaten panonuzda — yazmanız gerekmez.",
        ["ExtSetup.Step4"] = "Correntra simgesi göründüğünde bitti — bu pencere yeşile döner.",
        ["ExtSetup.Waiting"] = "Bağlantı bekleniyor… adımları tamamladıktan sonra birkaç saniye sürebilir.",
        ["ExtSetup.Connected"] = "Bağlandı! Artık tarayıcı indirmelerin yakalanıyor.",
        ["Settings.Browser.RunSetup"] = "Eklentiyi kur / yeniden kur…",
        ["VirusTotal.Clean"] = "VirusTotal: temiz ({0}/{1} motor)",
        ["VirusTotal.Detected"] = "VirusTotal UYARI: {0}/{1} motor bu dosyayı şüpheli buldu!",
        ["VirusTotal.Unknown"] = "VirusTotal: bu dosya henüz veri tabanında yok.",
        ["VirusTotal.Failed"] = "VirusTotal sorgusu başarısız: {0}",
        ["Settings.Updates.Heading"] = "GitHub üzerinden güncellemeler",
        ["Settings.Updates.AutoCheck"] = "Başlangıçta güncellemeleri denetle",
        ["Settings.Updates.Prerelease"] = "Ön sürümleri göster",
        ["Settings.Updates.Checking"] = "Güncellemeler denetleniyor…",
        ["Settings.Updates.Check"] = "Şimdi denetle",
        ["Settings.Updates.Current"] = "Yüklü sürüm: {0}",
        ["About.Title"] = "Correntra hakkında",
        ["About.Version"] = "Sürüm 0.1.0",
        ["About.Description"] = "Windows için hızlı, güvenli ve gizlilik odaklı indirme yöneticisi.",
        ["About.License"] = "Bağımsız olarak geliştirildi. Üçüncü taraf bileşen bildirimleri dağıtım paketinde bulunur.",
        ["About.Website"] = "Proje sayfasını aç",
    };

    private static Dictionary<string, string> English { get; } = new(StringComparer.Ordinal)
    {
        ["App.Name"] = "Correntra Downloader",
        ["App.Tagline"] = "Capture the stream. Finish fast.",
        ["Common.Add"] = "Add",
        ["Common.Apply"] = "Apply",
        ["Common.Browse"] = "Browse…",
        ["Common.Cancel"] = "Cancel",
        ["Common.Close"] = "Close",
        ["Common.Enabled"] = "Enabled",
        ["Common.No"] = "No",
        ["Common.Ok"] = "OK",
        ["Common.Save"] = "Save",
        ["Common.SelectAll"] = "Select all",
        ["Common.Yes"] = "Yes",
        ["Title.Minimize"] = "Minimize",
        ["Title.Maximize"] = "Maximize",
        ["Title.Restore"] = "Restore",
        ["Title.Close"] = "Close",
        ["Menu.Tasks"] = "Tasks",
        ["Menu.File"] = "File",
        ["Menu.Downloads"] = "Downloads",
        ["Menu.View"] = "View",
        ["Menu.Help"] = "Help",
        ["Menu.AddUrl"] = "Add URL…",
        ["Menu.Media"] = "Open captured media…",
        ["Menu.Import"] = "Import link list…",
        ["Menu.Exit"] = "Exit",
        ["Menu.OpenFile"] = "Open file",
        ["Menu.OpenFolder"] = "Open folder",
        ["Menu.Resume"] = "Resume",
        ["Menu.Pause"] = "Pause",
        ["Menu.Stop"] = "Stop",
        ["Menu.Delete"] = "Delete",
        ["Menu.DeleteCompleted"] = "Clear completed",
        ["Menu.SelectAll"] = "Select all",
        ["Menu.Options"] = "Options…",
        ["Menu.Scheduler"] = "Scheduler…",
        ["Menu.DarkTheme"] = "Dark theme",
        ["Menu.LightTheme"] = "Light theme",
        ["Menu.Turkish"] = "Türkçe",
        ["Menu.English"] = "English",
        ["Menu.About"] = "About Correntra",
        ["Toolbar.AddUrl"] = "Add URL",
        ["Toolbar.Resume"] = "Resume",
        ["Toolbar.Pause"] = "Pause",
        ["Toolbar.Stop"] = "Stop",
        ["Toolbar.Delete"] = "Delete",
        ["Toolbar.Options"] = "Options",
        ["Toolbar.Scheduler"] = "Schedule",
        ["Toolbar.StartQueue"] = "Start queue",
        ["Toolbar.StopQueue"] = "Stop queue",
        ["Toolbar.Media"] = "Media",
        ["Sidebar.Categories"] = "CATEGORIES",
        ["Category.All"] = "All Downloads",
        ["Category.Compressed"] = "Compressed",
        ["Category.Documents"] = "Documents",
        ["Category.Music"] = "Music",
        ["Category.Programs"] = "Programs",
        ["Category.Video"] = "Video",
        ["Category.Images"] = "Images",
        ["Category.Unfinished"] = "Unfinished",
        ["Category.Finished"] = "Finished",
        ["Category.Grabber"] = "Site grabber projects",
        ["Category.Queues"] = "Queues",
        ["Category.MainQueue"] = "Main queue",
        ["Search.Placeholder"] = "Search downloads",
        ["List.EmptyTitle"] = "Your download list is ready",
        ["List.EmptyBody"] = "Add a new link or start a download from the browser extension.",
        ["List.EmptyAction"] = "Add your first URL",
        ["Column.Name"] = "File name",
        ["Column.Category"] = "Category",
        ["Column.Size"] = "Size",
        ["Column.Status"] = "Status",
        ["Column.Progress"] = "Progress",
        ["Column.Remaining"] = "Time left",
        ["Column.Speed"] = "Transfer rate",
        ["Column.Added"] = "Added",
        ["Column.Description"] = "Description",
        ["Status.Ready"] = "Ready",
        ["Status.Selected"] = "{0} selected",
        ["Status.Total"] = "Total: {0}",
        ["Status.Active"] = "Active: {0}",
        ["Status.Speed"] = "Speed: {0}",
        ["Status.ExtensionConnected"] = "Browser capture enabled",
        ["Status.ExtensionDisconnected"] = "Waiting for browser",
        ["Status.AgentUnavailable"] = "Could not connect to Correntra Agent.",
        ["Status.CommandAccepted"] = "The request was sent to the background service.",
        ["Status.CommandRejected"] = "The request could not be completed: {0}",
        ["Status.UnknownError"] = "Unknown error",
        ["Status.CannotOpenFolder"] = "The folder could not be opened.",
        ["Status.CannotOpenFile"] = "The file could not be opened.",
        ["Menu.CopyUrl"] = "Copy download address",
        ["Menu.ShowInExplorer"] = "Show in folder",
        ["Menu.OpenContainingFolder"] = "Open folder",
        ["State.Pending"] = "Preparing",
        ["State.Queued"] = "Queued",
        ["State.NeedsInput"] = "Awaiting confirmation",
        ["State.Downloading"] = "Downloading",
        ["State.Finalizing"] = "Finalizing…",
        ["State.Paused"] = "Paused",
        ["State.Completed"] = "Completed",
        ["State.Failed"] = "Failed",
        ["State.Cancelled"] = "Cancelled",
        ["Update.Title"] = "A new Correntra version is ready",
        ["Update.Version"] = "Version {0}",
        ["Update.NoNotes"] = "No additional notes are available for this release.",
        ["Update.Later"] = "Later",
        ["Update.Install"] = "Install",
        ["Update.Toast.Heading"] = "{0} is out",
        ["Update.Toast.Body"] = "Correntra found a new version. Install it now?",
        ["Dialog.AddUrl.Title"] = "New download address",
        ["Dialog.AddUrl.Heading"] = "Add a link",
        ["Dialog.AddUrl.Description"] = "Paste an HTTP or HTTPS download address. The link is inspected safely before the download starts.",
        ["Dialog.AddUrl.Url"] = "Download address",
        ["Dialog.AddUrl.Placeholder"] = "https://example.com/file.zip",
        ["Dialog.AddUrl.FromClipboard"] = "Paste from clipboard",
        ["Dialog.AddUrl.Invalid"] = "Enter a valid HTTP or HTTPS address.",
        ["Dialog.Confirm.Title"] = "Download information",
        ["Dialog.Confirm.Heading"] = "File ready to download",
        ["Dialog.Confirm.Source"] = "Source",
        ["Dialog.Confirm.FileName"] = "File name",
        ["Dialog.Confirm.Category"] = "Category",
        ["Dialog.Confirm.Destination"] = "Save to",
        ["Dialog.Confirm.Size"] = "File size",
        ["Dialog.Confirm.UnknownSize"] = "Calculating…",
        ["Dialog.Confirm.Remember"] = "Remember this folder for this category",
        ["Dialog.Confirm.Now"] = "Start download",
        ["Dialog.Confirm.Later"] = "Download later",
        ["Dialog.Media.Title"] = "Media download options",
        ["Dialog.Media.Heading"] = "Choose quality and format",
        ["Dialog.Media.Description"] = "Video and audio tracks are merged automatically after the download finishes.",
        ["Dialog.Media.Video"] = "Video quality",
        ["Dialog.Media.Audio"] = "Audio quality",
        ["Dialog.Media.Format"] = "Output format",
        ["Dialog.Media.Subtitles"] = "Subtitles",
        ["Dialog.Media.AudioOnly"] = "Save audio only",
        ["Dialog.Media.Metadata"] = "Embed title, artist and cover art",
        ["Dialog.Media.Approximate"] = "Approximate size",
        ["Dialog.Media.Download"] = "Download media",
        ["Dialog.Schedule.Title"] = "Queue scheduler",
        ["Dialog.Schedule.Heading"] = "Main queue schedule",
        ["Dialog.Schedule.Enabled"] = "Enable schedule",
        ["Dialog.Schedule.Days"] = "Run on",
        ["Dialog.Schedule.Start"] = "Start",
        ["Dialog.Schedule.Stop"] = "Stop",
        ["Dialog.Schedule.Concurrent"] = "Concurrent downloads",
        ["Dialog.Schedule.SpeedLimit"] = "Speed limit (KB/s, 0 = unlimited)",
        ["Dialog.Schedule.Action"] = "When the queue completes",
        ["Dialog.Schedule.ActionNone"] = "Do nothing",
        ["Dialog.Schedule.ActionSleep"] = "Put the computer to sleep",
        ["Dialog.Schedule.ActionShutdown"] = "Shut down the computer",
        ["Day.Mon"] = "Mon",
        ["Day.Tue"] = "Tue",
        ["Day.Wed"] = "Wed",
        ["Day.Thu"] = "Thu",
        ["Day.Fri"] = "Fri",
        ["Day.Sat"] = "Sat",
        ["Day.Sun"] = "Sun",
        ["Settings.Title"] = "Correntra options",
        ["Settings.General"] = "General",
        ["Settings.Browser"] = "Browser",
        ["Settings.Transfers"] = "Transfers",
        ["Settings.Categories"] = "Categories",
        ["Settings.Scheduler"] = "Scheduler",
        ["Settings.Privacy"] = "Privacy",
        ["Settings.Updates"] = "Updates",
        ["Settings.General.Heading"] = "General behavior",
        ["Settings.General.StartWindows"] = "Start Correntra when Windows starts",
        ["Settings.General.Tray"] = "Minimize to the system tray when closing",
        ["Settings.General.Notifications"] = "Show a notification when a download completes",
        ["Settings.General.Clipboard"] = "Detect download links on the clipboard",
        ["Settings.General.Theme"] = "Appearance",
        ["Settings.General.Language"] = "Language",
        ["Settings.Browser.Heading"] = "Browser integration",
        ["Settings.Browser.Capture"] = "Take over Chrome and Edge downloads",
        ["Settings.Browser.Media"] = "Show the video/music download panel on pages",
        ["Settings.Browser.Session"] = "Use temporary session data for signed-in downloads",
        ["Settings.Browser.Exceptions"] = "Excluded sites",
        ["Settings.Browser.Extensions"] = "Excluded file extensions",
        ["Settings.Transfers.Heading"] = "Transfer performance",
        ["Settings.Transfers.Concurrent"] = "Maximum concurrent downloads",
        ["Settings.Transfers.Segments"] = "Connections per download",
        ["Settings.Transfers.GlobalLimit"] = "Global speed limit (KB/s, 0 = unlimited)",
        ["Settings.Transfers.Retry"] = "Automatically retry temporary errors",
        ["Settings.Categories.Heading"] = "File type routing",
        ["Settings.Categories.Description"] = "Extensions are routed to safe category folders under the default downloads folder.",
        ["Settings.Scheduler.Heading"] = "Queues and scheduling",
        ["Settings.Scheduler.Description"] = "Edit detailed day and time rules in Queue Scheduler.",
        ["Settings.Scheduler.Open"] = "Open scheduler",
        ["Settings.Privacy.Heading"] = "Privacy and diagnostics",
        ["Settings.Privacy.NoAds"] = "Correntra contains no advertising or user tracking.",
        ["Settings.Privacy.Crash"] = "Send a crash report only after I approve it",
        ["Settings.Privacy.History"] = "Keep completed download history",
        ["Settings.Privacy.Clear"] = "Clear local history",
        ["Settings.VirusTotal.Heading"] = "VirusTotal scanning (optional)",
        ["Settings.VirusTotal.Enable"] = "Check completed downloads with VirusTotal",
        ["Settings.VirusTotal.ApiKey"] = "VirusTotal API key (only the file's SHA-256 digest is sent)",
        ["Settings.VirusTotal.Get"] = "Get a free key",
        ["ExtSetup.Title"] = "Browser extension setup",
        ["ExtSetup.Heading"] = "Enable browser capture",
        ["ExtSetup.Subtitle"] = "Route downloads and videos from Chrome/Edge into Correntra. Takes about 30 seconds.",
        ["ExtSetup.BrowserLine"] = "Detected browsers: {0}",
        ["ExtSetup.NoBrowser"] = "No Chromium browser found (install Chrome, Edge or Brave)",
        ["ExtSetup.Step1"] = "Open the extension folder (its path was copied to your clipboard)",
        ["ExtSetup.OpenFolder"] = "Open folder",
        ["ExtSetup.Step2"] = "Open chrome://extensions and turn on Developer mode (top right)",
        ["ExtSetup.OpenPage"] = "Open the extensions page",
        ["ExtSetup.Step3"] = "Click \"Load unpacked\", paste (Ctrl+V) and select the folder",
        ["ExtSetup.PathCopied"] = "The path is already on your clipboard — no typing needed.",
        ["ExtSetup.Step4"] = "When the Correntra icon appears you are done — this window turns green.",
        ["ExtSetup.Waiting"] = "Waiting for connection… this can take a few seconds after the steps.",
        ["ExtSetup.Connected"] = "Connected! Browser downloads are now captured.",
        ["Settings.Browser.RunSetup"] = "Set up / repair the extension…",
        ["VirusTotal.Clean"] = "VirusTotal: clean ({0}/{1} engines)",
        ["VirusTotal.Detected"] = "VirusTotal WARNING: {0}/{1} engines flag this file!",
        ["VirusTotal.Unknown"] = "VirusTotal: this file is not in their database yet.",
        ["VirusTotal.Failed"] = "VirusTotal lookup failed: {0}",
        ["Settings.Updates.Heading"] = "Updates through GitHub",
        ["Settings.Updates.AutoCheck"] = "Check for updates at startup",
        ["Settings.Updates.Prerelease"] = "Show pre-release versions",
        ["Settings.Updates.Checking"] = "Checking for updates…",
        ["Settings.Updates.Check"] = "Check now",
        ["Settings.Updates.Current"] = "Installed version: {0}",
        ["About.Title"] = "About Correntra",
        ["About.Version"] = "Version 0.1.0",
        ["About.Description"] = "A fast, secure and privacy-minded download manager for Windows.",
        ["About.License"] = "Independently developed. Third-party component notices are included with the distribution.",
        ["About.Website"] = "Open project page",
    };
}
